name: Generate Snake Dark

on:
  schedule:
    - cron: "0 */12 * * *"  # esegue ogni 12 ore
  workflow_dispatch:
  push:

permissions:
  contents: write  # permette al bot di fare push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona il repository
      - uses: actions/checkout@v3

      # Genera il banner Snake scuro
      - name: Generate Snake Dark
        uses: Platane/snk@v3
        with:
          github_user_name: 4137314
          outputs: output/github-contribution-grid-snake-dark.svg
          theme: dark

      # Commit e push dei file generati
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "output"
          message: "Update Snake Dark"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
